% Generate deterministic MATLAB reference outputs for the Python parity tests.

script_directory = fileparts(mfilename('fullpath'));
tests_directory = fileparts(script_directory);
python_directory = fileparts(tests_directory);
toolbox_directory = fileparts(python_directory);

addpath(fullfile(toolbox_directory,'FREQNESS_Functions'));
addpath(fullfile(toolbox_directory,'FREQNESS_ExternalFunctions'));

srate = 64;
time = (0:255)/srate;

subject_1 = [ ...
    sin(2*pi*3*time) + .20*cos(2*pi*11*time); ...
    cos(2*pi*5*time) + .10*sin(2*pi*17*time); ...
    .70*sin(2*pi*8*time + .3) + .30*cos(2*pi*2*time); ...
    .40*cos(2*pi*13*time - .2) + .20*sin(2*pi*7*time)];

subject_2 = [ ...
    .90*sin(2*pi*3*time + .2) + .25*cos(2*pi*11*time); ...
    1.10*cos(2*pi*5*time - .1) + .15*sin(2*pi*17*time); ...
    .60*sin(2*pi*8*time + .5) + .35*cos(2*pi*2*time); ...
    .45*cos(2*pi*13*time - .4) + .18*sin(2*pi*7*time)];

data = cat(3,subject_1,subject_2);
frex = [5 10];
fwidth = [1 2];
bad_segments = [1 25];

FREQ = FREQNESS_NetworkEstimation( ...
    data,frex,srate, ...
    'fwidth',fwidth, ...
    'regularisation',.01, ...
    'ncomps',3, ...
    'bad_segments',bad_segments);

[filter_data,filter_empirical,filter_kernel] = filterFGx( ...
    subject_1,srate,8,1.5,false);

fixture_directory = fullfile(tests_directory,'fixtures');
if ~exist(fixture_directory,'dir')
    mkdir(fixture_directory);
end

save( ...
    fullfile(fixture_directory,'matlab_core_reference.mat'), ...
    'data','frex','fwidth','srate','bad_segments','FREQ', ...
    'filter_data','filter_empirical','filter_kernel','-v7');

