function call = buildSecondaryFunctionCall(configuration,FREQ,MNI,events, ...
        sourceData)
%BUILDSECONDARYFUNCTIONCALL Translate one GUI configuration to backend inputs.

if ~isstruct(configuration) || ~isfield(configuration,'moduleId') || ...
        ~isfield(configuration,'values') || ...
        ~isfield(configuration,'selectedFrequencies')
    error('FREQNESS:GUI:InvalidSecondaryConfig', ...
        'The secondary-analysis configuration is incomplete.');
end
if ~isstruct(FREQ)
    error('FREQNESS:GUI:InvalidParticipantFREQ', ...
        'A combined FREQ structure is required.');
end
if nargin < 3
    MNI = [];
end
if nargin < 4
    events = [];
end
if nargin < 5
    sourceData = [];
end

moduleId = lower(char(configuration.moduleId));
values = configuration.values;
selected = configuration.selectedFrequencies;
call = struct('functionName','','arguments',{{}},'outputNames',{{}});

switch moduleId
    case 'entropy'
        call.functionName = 'FREQNESS_EntropyLandscape';
        call.arguments = {FREQ,'plot_all',values.plotAll};
        call.outputNames = {'H2','ED'};

    case 'exponential_dk'
        call.functionName = 'FREQNESS_ExponentialDK';
        call.arguments = {FREQ, ...
            'which_comp',values.whichComponent, ...
            'range2fit',values.fitRange, ...
            'plot_all',values.plotAll};
        call.outputNames = {'decayCoeff','goodFit'};

    case 'freq_gradients'
        call.functionName = 'FREQNESS_FreqGradients';
        call.arguments = {FREQ,MNI, ...
            'frex2model',values.frequencyRange, ...
            'comp2model',values.component, ...
            'threshold_sd',values.thresholdSD, ...
            'plot_all',values.plotAll};
        call.outputNames = {'gradCoeff','goodFit'};

    case 'comp_gradients'
        componentRange = [min(values.components) max(values.components)];
        call.functionName = 'FREQNESS_CompGradients';
        call.arguments = {FREQ,MNI, ...
            'freq2model',values.frequency, ...
            'comps2model',componentRange, ...
            'threshold_sd',values.thresholdSD, ...
            'plot_all',values.plotAll};
        call.outputNames = {'gradCoeff','goodFit'};

    case 'cross_coupling'
        call.functionName = 'FREQNESS_CrossCoupling';
        call.arguments = {FREQ,values.lfoFrequency, ...
            'mni',MNI, ...
            'frex2model',values.carrierRange, ...
            'which_comp',values.component, ...
            'plot_all',values.plotAll, ...
            'nbins',values.phaseBins, ...
            'min_valid_bins',values.minimumValidBins};
        call.outputNames = {'CFC'};

    case 'induced_responses'
        call.functionName = 'FREQNESS_InducedResponses';
        call.arguments = {FREQ,events,values.epochWindow, ...
            values.baselineWindow, ...
            'which_comp',values.components, ...
            'frex2model',values.frequencyRange, ...
            'keep_trials',values.keepTrials, ...
            'scale_max',values.scaleMaximum, ...
            'plot_avg',values.plotAverage, ...
            'plot_all',values.plotAll};
        call.outputNames = {'IND'};

    case 'backprojection'
        call.functionName = 'FREQNESS_BackProjection';
        call.arguments = {FREQ,values.frequency, ...
            'comps2project',values.components};
        call.outputNames = {'backProj'};

    case 'network_removal'
        call.functionName = 'FREQNESS_NetworkRemoval';
        call.arguments = {FREQ,sourceData,values.frequency, ...
            'comps2remove',values.components};
        call.outputNames = {'dataClean','removedActivity'};

    case 'visualizer'
        Landscape = struct( ...
            'frex',selected.landscapeRange, ...
            'ncomps',values.landscapeComponents);
        if values.includePatterns
            Patterns = struct( ...
                'MNI_coords',MNI, ...
                'frex',selected.patternRange, ...
                'ncomps',values.patternComponents, ...
                'path_output',configuration.outputFolder);
        else
            Patterns = [];
        end
        call.functionName = 'FREQNESS_Visualizer';
        call.arguments = {FREQ,Landscape,Patterns, ...
            'plot_all',values.plotAll, ...
            'threshold_sd',values.thresholdSD, ...
            'save_nifti',values.saveNifti};
        call.outputNames = {};

    otherwise
        error('FREQNESS:GUI:UnknownSecondaryModule', ...
            'Unknown secondary-analysis module: %s.',moduleId);
end

end
