function [process,control] = launchNetworkEstimationProcess( ...
        dataset,configuration,cancellationFile)
%LAUNCHNETWORKESTIMATIONPROCESS Serialize and start a core-analysis job.

outputFolder = configuration.outputFolder;
if isempty(outputFolder)
    outputFolder = dataset.networkFolder;
end
job = struct( ...
    'dataset',dataset, ...
    'configuration',configuration, ...
    'cancellationFile',cancellationFile);
[process,control] = freqnessgui.launchAnalysisProcess( ...
    job,outputFolder,'freqnessgui.runNetworkEstimationProcess', ...
    'FREQNESS_Background.log');

end
