function [process,control] = launchSecondaryAnalysisProcess( ...
        networkSet,configuration,MNI,cancellationFile)
%LAUNCHSECONDARYANALYSISPROCESS Serialize and start a secondary-analysis job.

job = struct( ...
    'networkSet',networkSet, ...
    'configuration',configuration, ...
    'MNI',MNI, ...
    'cancellationFile',cancellationFile);
[process,control] = freqnessgui.launchAnalysisProcess( ...
    job,configuration.outputFolder, ...
    'freqnessgui.runSecondaryAnalysisProcess', ...
    'FREQNESS_Background.log');

end
