function schema = secondaryModuleSchema(moduleId,context)
%SECONDARYMODULESCHEMA Describe one dynamic secondary-analysis form.

if nargin < 2 || isempty(context)
    context = struct();
end
frequencies = contextValue(context,'frequencies',1.2:1.2:24);
frequencies = frequencies(:)';
if isempty(frequencies)
    frequencies = 1.2:1.2:24;
end
nComponents = contextValue(context,'nComponents',30);
if isempty(nComponents) || ~isfinite(nComponents) || nComponents < 1
    nComponents = 30;
end
nComponents = round(nComponents);
frequencyRange = [frequencies(1) frequencies(end)];
defaultComponents = sprintf('1:%d',min(3,nComponents));

emptyFields = repmat(fieldTemplate(),0,1);
schema = struct('mandatory',emptyFields,'optional',emptyFields);
moduleId = lower(char(moduleId));

switch moduleId
    case 'entropy'
        schema.optional = makeField('plotAll','Plot every participant', ...
            'logical',false,'Also create participant-level entropy figures.');

    case 'exponential_dk'
        schema.optional = [ ...
            makeField('whichComponent','Component','component',1, ...
                'Component whose decay profile is summarized.'), ...
            makeField('fitRange','Frequency range to fit','frequencyRange', ...
                frequencyRange,'Empty backend defaults are represented by the full range.'), ...
            makeField('plotAll','Plot every participant','logical',false, ...
                'Also create participant-level decay figures.')];

    case 'freq_gradients'
        schema.optional = [ ...
            makeField('frequencyRange','Frequencies to model','frequencyRange', ...
                frequencyRange,'Model the closest available frequencies in this range.'), ...
            makeField('component','Component','component',1, ...
                'Component whose spatial pattern is modeled.'), ...
            makeField('thresholdSD','Pattern threshold (SD)','number',1, ...
                'Retain normalized pattern coefficients above this threshold.'), ...
            makeField('plotAll','Plot every participant','logical',false, ...
                'Also create participant-level spatial figures.')];

    case 'comp_gradients'
        schema.optional = [ ...
            makeField('frequency','Frequency to model','frequency',frequencies(1), ...
                'The closest available network frequency is used.'), ...
            makeField('components','Components to model','componentVector', ...
                defaultComponents, ...
                'One contiguous component range, for example 1:5.'), ...
            makeField('thresholdSD','Pattern threshold (SD)','number',2, ...
                'Retain normalized pattern coefficients above this threshold.'), ...
            makeField('plotAll','Plot every participant','logical',false, ...
                'Also create participant-level spatial figures.')];

    case 'cross_coupling'
        schema.mandatory = makeField('lfoFrequency','LFO frequency', ...
            'frequency',frequencies(1),'Low-frequency phase network.');
        schema.optional = [ ...
            makeField('carrierRange','Carrier-frequency range', ...
                'frequencyRange',frequencyRange, ...
                'Carrier networks included in the coupling model.'), ...
            makeField('component','Component','component',1, ...
                'Component used as both modulator and carrier.'), ...
            makeField('phaseBins','Phase bins','integer',37, ...
                'Number of bins spanning the LFO phase cycle.'), ...
            makeField('minimumValidBins','Minimum valid bins','numberOrEmpty','', ...
                'Empty uses max(6, ceil(phase bins / 2)).'), ...
            makeField('plotAll','Plot every participant','logical',false, ...
                'Also create participant-level coupling figures.')];

    case 'backprojection'
        schema.mandatory = makeField('frequency','Frequency to project', ...
            'frequency',frequencies(1),'The closest available frequency is used.');
        schema.optional = makeField('components','Components to project', ...
            'componentVector','1','Selected voxel-space contributions are summed.');

    case 'network_removal'
        schema.mandatory = makeField('frequency','Frequency to remove', ...
            'frequency',frequencies(1),'The closest available frequency is used.');
        schema.optional = makeField('components','Components to remove', ...
            'componentVector','1','Components removed from the original broadband data.');

    case 'induced_responses'
        schema.mandatory = [ ...
            makeField('eventsFile','Events file','file','', ...
                'MAT-file containing participant event-onset samples.'), ...
            makeField('epochWindow','Epoch window (s)','timeRange',[-0.1 3.4], ...
                'Two endpoints relative to event onset.'), ...
            makeField('baselineWindow','Baseline window (s)','timeRange',[-0.1 0], ...
                'Baseline interval relative to event onset.')];
        schema.optional = [ ...
            makeField('components','Components','componentVector','1', ...
                'One or more components to analyze.'), ...
            makeField('frequencyRange','Frequencies','frequencyRange', ...
                frequencyRange,'Frequencies included in the response.'), ...
            makeField('keepTrials','Retain single trials','logical',false, ...
                'Save participant-level single-trial power.'), ...
            makeField('scaleMaximum','Also scale by maximum','logical',false, ...
                'Retain an additional maximum-scaled result.'), ...
            makeField('plotAverage','Plot group average','logical',false, ...
                'Create grand-average time-frequency maps.'), ...
            makeField('plotAll','Plot every participant','logical',false, ...
                'Create participant-level time-frequency maps.')];

    case 'visualizer'
        schema.mandatory = [ ...
            makeField('landscapeRange','Landscape frequencies', ...
                'frequencyRange',frequencyRange, ...
                'Frequency interval shown in the network landscape.'), ...
            makeField('landscapeComponents','Landscape component count', ...
                'component',min(3,nComponents), ...
                'Plot components 1 through this retained component count.')];
        schema.optional = [ ...
            makeField('includePatterns','Include spatial patterns', ...
                'logical',true,'Use the active MNI coordinates for spatial maps.'), ...
            makeField('patternRange','Pattern frequencies', ...
                'frequencyRange',frequencyRange, ...
                'Frequency interval used for spatial maps.'), ...
            makeField('patternComponents','Pattern component count', ...
                'component',1, ...
                'Plot components 1 through this retained component count.'), ...
            makeField('thresholdSD','Activation threshold (SD)', ...
                'number',1,'Spatial activation threshold in standard deviations.'), ...
            makeField('plotAll','Plot every participant','logical',false, ...
                'Also create participant-level figures.'), ...
            makeField('saveNifti','Save NIFTI maps','logical',true, ...
                'Available for the bundled MNI152 8-mm source space.')];

    otherwise
        error('FREQNESS:GUI:UnknownSecondaryModule', ...
            'Unknown secondary-analysis module: %s.',moduleId);
end

end

function field = fieldTemplate()
field = struct('key','','label','','type','','default',[], ...
    'help','');
end

function field = makeField(key,label,type,defaultValue,helpText)
field = fieldTemplate();
field.key = key;
field.label = label;
field.type = type;
field.default = defaultValue;
field.help = helpText;
end

function value = contextValue(context,fieldName,defaultValue)
if isstruct(context) && isfield(context,fieldName) && ...
        ~isempty(context.(fieldName))
    value = context.(fieldName);
else
    value = defaultValue;
end
end
