function validateNetworkConfig(config,dataset)
%VALIDATENETWORKCONFIG Validate settings before starting a long analysis.

if ~isstruct(dataset) || ~isfield(dataset,'isValid') || ~dataset.isValid
    error('FREQNESS:GUI:InvalidDataset', ...
        'Every participant file must pass dataset validation before analysis.');
end

requiredNetworkFields = {'frequencies','samplingRate','duration','fwidth', ...
    'filter','regularisation','ncomps','badSegments','rescale'};
for fieldi = 1:numel(requiredNetworkFields)
    if ~isfield(config.network,requiredNetworkFields{fieldi})
        error('FREQNESS:GUI:MissingConfig', ...
            'Missing network setting: %s.',requiredNetworkFields{fieldi});
    end
end

network = config.network;
frequencies = network.frequencies;
srate = network.samplingRate;

if ~isnumeric(frequencies) || ~isreal(frequencies) || isempty(frequencies) || ...
        ~isvector(frequencies) || any(~isfinite(frequencies)) || any(frequencies <= 0)
    error('FREQNESS:GUI:InvalidConfig', ...
        'Frequencies must be a non-empty vector of positive finite values.');
end
if ~isnumeric(srate) || ~isreal(srate) || ~isscalar(srate) || ...
        ~isfinite(srate) || srate <= 0
    error('FREQNESS:GUI:InvalidConfig', ...
        'Sampling rate must be one positive finite value.');
end
if any(frequencies >= srate/2)
    error('FREQNESS:GUI:InvalidConfig', ...
        'Every frequency must be below the Nyquist frequency (%.4g Hz).',srate/2);
end

if ~isempty(network.duration) && (~isnumeric(network.duration) || ...
        ~isreal(network.duration) || ~isscalar(network.duration) || ...
        ~isfinite(network.duration) || network.duration <= 0)
    error('FREQNESS:GUI:InvalidConfig', ...
        'Duration must be empty or one positive finite value in seconds.');
end

if ~isempty(network.fwidth) && (~isnumeric(network.fwidth) || ...
        ~isreal(network.fwidth) || any(~isfinite(network.fwidth)) || ...
        any(network.fwidth <= 0) || ...
        ~(isscalar(network.fwidth) || numel(network.fwidth) == numel(frequencies)))
    error('FREQNESS:GUI:InvalidConfig', ...
        'Filter width must be empty, scalar, or contain one positive value per frequency.');
end

if ~(ischar(network.filter) || ...
        (isstring(network.filter) && isscalar(network.filter))) || ...
        ~ismember(lower(char(network.filter)),{'logarithmic','linear'})
    error('FREQNESS:GUI:InvalidConfig', ...
        'Filter progression must be logarithmic or linear.');
end

if ~isnumeric(network.regularisation) || ~isscalar(network.regularisation) || ...
        ~isfinite(network.regularisation) || network.regularisation < 0 || ...
        network.regularisation >= 1
    error('FREQNESS:GUI:InvalidConfig', ...
        'Regularisation must be in the interval [0, 1).');
end

if ~isnumeric(network.ncomps) || ~isscalar(network.ncomps) || ...
        ~isfinite(network.ncomps) || network.ncomps < 1 || ...
        network.ncomps ~= round(network.ncomps)
    error('FREQNESS:GUI:InvalidConfig', ...
        'Retained components must be one positive integer.');
end

rowCounts = arrayfun(@(participant)participant.dataSize(1), ...
    dataset.participants);
if network.ncomps > min(rowCounts)
    error('FREQNESS:GUI:InvalidConfig', ...
        'Retained components cannot exceed the smallest voxel count (%d).', ...
        min(rowCounts));
end

if ~isempty(network.badSegments) && (~isnumeric(network.badSegments) || ...
        ~isreal(network.badSegments) || ~isvector(network.badSegments) || ...
        any(~isfinite(network.badSegments)) || ...
        any(network.badSegments ~= round(network.badSegments)) || ...
        any(network.badSegments < 1))
    error('FREQNESS:GUI:InvalidConfig', ...
        'Bad segments must contain positive integer sample indices.');
end

if ~islogical(network.rescale) || ~isscalar(network.rescale)
    error('FREQNESS:GUI:InvalidConfig','Rescale must be one logical value.');
end

timeCounts = arrayfun(@(participant)participant.dataSize(2), ...
    dataset.participants);
if isempty(network.duration)
    analyzedSamples = timeCounts;
else
    requestedSamples = network.duration*srate;
    if abs(requestedSamples-round(requestedSamples)) > eps(max(1,requestedSamples))
        error('FREQNESS:GUI:InvalidConfig', ...
            'Duration multiplied by sampling rate must be an integer number of samples.');
    end
    requestedSamples = round(requestedSamples);
    if any(requestedSamples > timeCounts)
        error('FREQNESS:GUI:InvalidConfig', ...
            'Requested duration exceeds at least one participant recording.');
    end
    analyzedSamples = repmat(requestedSamples,size(timeCounts));
end

if ~isempty(network.badSegments) && any(max(network.badSegments) > analyzedSamples)
    error('FREQNESS:GUI:InvalidConfig', ...
        'A bad-segment index exceeds at least one participant analysis duration.');
end

end
